### PR TITLE
semantics: make match only be a statement

### PR DESCRIPTION
**Pull request by zkat**
yep.

This also changes the syntax significantly.

Hooray

### CODE REVIEW

**Comment by sebmarkbage** [comment]
Is there a rationale here that you can link to?

**Comment by sebmarkbage** [comment]
Some thoughts:

Love the `when` because it leaves shorter syntax open for the brand checking mechanism in the future.

The `~>` is not great for many keyboards. It's a hard thing to type. The whole arrow syntax likeliness seems overloaded in JS to me. Other languages have other forms of arrows and we might even want them. We shouldn't take adding them and overloading them lightly though. Would just a colon work now that you have the contextual keyword?

Is this statement form a temporary form to allow for more things turning into expression forms with do/if/etc in the future as a separate proposal? Or do you see this design as permanent?

**Comment by dantman** [comment]
- `MatchClause` states `where`, examples state `when`.
- I like the idea of adding a token before the pattern (after all my preference is `case (foo) { match {x:1}: doFo(); }`). I'm iffy on `when` for pattern matching given the prior art of `when` being equivalent to `case`, `if`, or `switch` in other languages like Ruby, Perl, SQL, and Kotlin. But being used for pattern matching here.
- The idea of accepting only a single Statement sounds really strange to me. Is there any other syntax in JavaScript that works that way? We have bodies that accepts multiple statements. And we already have syntax that can be an Expression or a `{}` Block. But I can't think of any syntax that only accepts a singular Statement.

**Comment by zkat** [comment]
@sebmarkbage I intend to write a longer rationale for this before merging it. I was just getting the PR up before I left work. I think it's also important for me to clarify that literally nothing I'm doing is permanent. I think it's important to move around a lot while I still can and there's a lot of weird constraints to work through. And yes, I'm very much designing this with the idea that match will eventually work as an expression -- but I think the way it does that should be the same as however we end up doing it for if/switch/for/etc.

@dantman I copied what `if` does. You can have multiple statements using blocks, just like with `if`.

**Comment by sebmarkbage** [comment]
I like the premise of outsourcing related complexities. That has worked well recently. However just beware that there is a recent turn against that style in proposals because it doesn’t let cross cutting concerns be fully resolved. So those things might in practice hold this proposal in the later stages for a long time to iron it out. That’s not a bad thing though. There’s many other things to discuss anyway.

**Comment by thers** [comment]
Sorry if I'm missing something, but how still can't fully understand why is it necessary to make it statement instead of expression. The only good argument I've heard is that it won't play nicely with various control structures like if/while/for.

Following the argument "without affecting other parts of the language" I can't see how it can be used as an expression in the future. Wrapping the whole statement with braces would affect other parts of the language, same goes for distinguishing expression from statement based on the context it's used in.

And I think not only "pattern" part of this feature is important but also it being an expression.

**Comment by zkat** [comment]
If you see the text in the PR, I wrote a good chunk of text on the rationale behind this, which you can reference for my main reasons. Since you don't address those directly, I'm assuming you didn't read it.

**Comment by thers** [comment]
Correct, missed that bit. It doesn't look that bad now when combined with do expressions :)

**Comment by jeffvandyke** [comment]
I've read the pull request, and I am curious, for clarity's sake, whether the match statement will *eventually* be an expression, similar to how it is in other languages. I agree that some of the semantics are better discussed in the focused scope of [proposal-do-expressions](https://github.com/tc39/proposal-do-expressions), but once those semantics become clear, I think it would be convenient to have this proposal follow/reuse those semantics as well, especially considering the way that `match` works as an expression in other languages. Is that the eventual plan?

**Comment by zkat** [comment]
That is the intention. match will benefit enormously from being an expression once there's a good way to do that

**Comment by zkat** [comment]
@joshburgess if you "just want them", then Babel should be good enough, imo. There's even already ongoing work to implement this in Babel. I think it's important to consider a language as a whole, and the impact when people approach that language with all its features, rather than throwing random things into a ball of mud and shrug it off. The focus on the core functionality of the statement is hugely beneficial, too, by reducing noise around the discussion.

I think there's significant risk for pain for users, in the long term, if there's an inconsistency between match's expression style, and what _all other conditionals_ do. I am not expecting this proposal to land in the next year or two. This is more of a gardening thing, and it takes time -- so making that kind of sacrifice for the sake of expediency would be counterproductive.

The `do{}` expression proposal isn't just a random idea, it is where the actual problems with doing this sort of thing are getting resolved. If it's getting held up by the answers to those questions, I don't expect that problem to be any different if I try it in my own corner.

**Comment by vincentdchan** [comment]
@joshburgess There is an babel implementation of original proposal [https://github.com/babel/babel/pull/7633](https://github.com/babel/babel/pull/7633), maybe it's what you want, and that's also what I expect. 😂

@zkat There's many reasons that it becomes an `statement`. I read them, but I still felt strange, it's just like a new version of `switch`, but not the concept of `match`. Yep I know it's not the final version, so I am looking forward to it.

**Comment by joshburgess** [comment]
@vincentdchan I agree that it just seems like a slightly more feature-rich version of switch. It's not what I would expect from a pattern matching feature... That's the only reason why I'm complaining...

**Comment by zkat** [comment]
@joshburgess I would rather people pour their energy into a coherent `do {}` proposal and associated "implicit `do {}`" for built-in statements. If the `do {}` proposal dies a horrible, lonely death, then my answer would be "give me a proposal that turns all of these statements into expressions, and make sure to include `match`". The goal, remember, is to piggyback on whatever proposal turns `match`'s siblings into first-class expressions. All of them. Not a halfassed "oh these kinda do, these kinda don't, the expression handling on this one works this way, but that other one breaks if you do it that way...". Let's do things right here.

The match proposal is written to closely mirror other constructs so that whatever solution we come to is likely to be compatible across the board.

And if that doesn't go through either, there's still fat arrows, or `eval` if you want the `CompletionValue` :)

**Comment by zkat** [comment]
and for the record, I am totally here for "souped up `switch` statement without the bizarre fallthrough logic". It's literally a thing I've wanted for forever and a day. If that's all match amounts to (which I don't think is likely in the long term, and we _are_ talking long term for all of this, including `match` ratification), then it will will be worth it for me to have it in the language.

I'm still gonna try and get all the things I want out of it, though. I just can't promise anything.

**Comment by ForsakenHarmony** [comment]
wait maybe I'm missing something, but why was the `when` added?

**Pull request merged**
