### PR TITLE
Fix typo in regex example

### PR DESCRIPTION
**Pull request by qwales1**
I think this should be `with` instead of `as`

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
No, it should not. The difference is that `as` provides bindings. `with` chains the pattern, which would match against it.

A way to see the difference is, let's say i typoed one of the binding names:
```jsx
when (/(?<left>\d+) \+ (?<right>\d+)/) as { groups: { leftt, right } }
// this would match, but the `leftt` binding would be undefined
```
vs
```jsx
when (/(?<left>\d+) \+ (?<right>\d+)/) with { groups: { leftt, right } }
// this would fail to match entirely, and it would proceed to the next `when`.
```

In other words, this is very intentional as-is.

**Comment by qwales1** [comment]
@ljharb Got it. Thanks for the explanation. I think I was confused because the following paragraphs reference the `with` keyword.

**Comment by treybrisbane** [comment]
>the following paragraphs reference the with keyword

Yeah I noticed this as well. It does seem like _something_ needs tweaking here, even if it's not what this PR tweaked?

**Comment by ljharb** [comment]
If you’d like to reopen and update the PR to update the text instead, that’d be great :-)

**Comment by tabatkins** [comment]
No, this is a mistake in the example. The `as` binds the value *before* the matcher is applied. This example means to say `with`, as it's dealing with the result of the matcher.

**Comment by ljharb** [comment]
@tabatkins i don't agree; the `as` can't affect anything to its left, and there are no patterns to its right. `as` _after_ the pattern absolutely is intended to handle the result of the matcher.

**Comment by ljharb** [comment]
Closing, since we've dropped `as`.

**Pull request closed without merging**
